// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <Secret.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = SECRET_SSID;          // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS; // Network password (use for WPA, or use as key for WEP)

void onLedChange();
void onNoInternetExampleChange();

bool led;
bool noInternetExample;

void initProperties()
{
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(noInternetExample, READWRITE, ON_CHANGE, onNoInternetExampleChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);